name: lya_encuestas
app_name: Transportistas APP
description: Aplicación para transportistas

publish_to: 'none'

version: 1.1.2

environment:
  sdk: ">=2.16.0-134.1.beta <3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  sqflite:
  path:
  sn_progress_dialog: ^1.0.3
  simple_animations: ^4.0.1
  awesome_drawer_bar: 
  animated_theme_switcher: ^2.0.1-nullsafety.0
  provider: ^5.0.0
  intl: ^0.17.0
  percent_indicator: ^4.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  modal_bottom_sheet: ^2.0.1
  flutter_image_compress: ^1.1.1
  flutter_svg: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.0
#  path_provider: ^1.6.27
  intl: ^0.17.0
#  bluetooth_print: 3.0.1
  http: ^0.13.4

flutter:
 uses-material-design: true
 assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/